listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# Enjaular a los usuarios en su carpeta personal
chroot_local_user=YES
allow_writeable_chroot=YES

# Configuración del Modo Pasivo (Para que funcione tras el Firewall)
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=50000
# pasv_address=192.168.100.10 # Descomentar si el cliente está fuera de la red local

secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO
