# --- CONFIGURACIÓN GLOBAL ---
interface=enp0s3
listen-address=127.0.0.1,192.168.1.10
bind-interfaces
domain-needed
bogus-priv

# --- CONFIGURACIÓN DHCP ---
# Repartir IPs desde la .30 hasta la .130, con una cadencia de 12 horas
dhcp-range=192.168.1.30,192.168.1.130,255.255.255.0,12h

# Decirle a los clientes que la Puerta de Enlace (Router) es el Firewall
dhcp-option=option:router,192.168.1.1

# Decirle a los clientes que este mismo servidor es el DNS
dhcp-option=option:dns-server,192.168.1.10

# --- CONFIGURACIÓN DNS (Resolución Local DMZ) ---
# Engañamos a la red local: cuando pregunten por estos dominios, los enviamos a la IP de la DMZ
address=/site1.hosting.local/192.168.100.10
address=/site2.hosting.local/192.168.100.10
