#!/usr/sbin/nft -f

# Limpiamos reglas anteriores para evitar duplicados
flush ruleset

# --- 1. DEFINICIÓN DE VARIABLES ---
define WAN = "enp0s3"
define DMZ = "enp0s8"
define LAN = "enp0s9"

# Direcciones IP clave del proyecto
define SRV_DMZ = 192.168.100.10

# Agrupación de puertos
define WEBPORTS = { 80, 443 }
define FTPPORTS = { 20, 21 }


# --- 2. TABLA DE FILTRADO (Seguridad) ---
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        ct state established,related accept
        iifname "lo" accept

        # Permitir hacer Ping al Firewall desde la LAN y la DMZ para pruebas
        iifname { $LAN } ip protocol icmp accept

        # Permitir gestión del Firewall por SSH (22) y el Túnel Inverso de la DMZ (2222)
        tcp dport { 22, 2222 } ct state new accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state established,related accept
        ip saddr 192.168.100.10 ip daddr 192.168.1.31 tcp dport 22 accept
        # Permitir a la LAN y a la DMZ salir a Internet
        iifname { $LAN, $DMZ } oifname $WAN accept
        iifname $LAN oifname $DMZ tcp dport 40000-50000 accept
        # Permitir tráfico de LAN a DMZ solo para Web y FTP
        iifname $LAN oifname $DMZ tcp dport $WEBPORTS accept
        iifname $LAN oifname $DMZ tcp dport $FTPPORTS accept

        # Seguridad estricta: Bloquear cualquier inicio de conexión de DMZ a LAN
        iifname $DMZ oifname $LAN drop
    }

    chain output {
        # Dejamos que el firewall pueda salir a internet para actualizarse (apt update)
        type filter hook output priority 0; policy accept;
    }
}


# --- 3. TABLA NAT (Enrutamiento y Redirección) ---
table ip nat {
    chain prerouting {
        type nat hook prerouting priority -100; policy accept;

        # Redirigir peticiones Web desde Internet (WAN) hacia el Servidor DMZ
        iifname $WAN tcp dport $WEBPORTS dnat to $SRV_DMZ
    }

    chain postrouting {
        type nat hook postrouting priority 100; policy accept;

        # Enmascarar todo el tráfico que sale hacia Internet con la IP de la WAN
        oifname $WAN masquerade
    }
}

